Vagrant.configure("2") do |config|
  config.vm.box = "pxfs/freebsd-13.0"
  config.vm.box_version = "0.0.4"
  config.vm.box_check_update = false

  config.vm.guest = "freebsd"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provision "shell", inline: "pkg install -y git"
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 7 * 1024 * 0.75
  end

  config.ssh.shell = "su -"
  config.ssh.insert_key = false
end
