Vagrant.configure("2") do |config|
  config.vm.guest = "freebsd"

  config.vm.box = "emulate/freebsd-13.0"
  config.vm.ignore_box_vagrantfile = true
  config.vm.box_check_update = false
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "31ca8f6e843c0ce3533da9222f7a7d0c18153246736a1d1bfc97b586de4c523c"
  config.vm.box_url = [
    "https://app.vagrantup.com/emulate/boxes/freebsd-13.0/versions/0.1.2/providers/virtualbox.box",
    "https://github.com/mario-campos/emulate/releases/download/freebsd-13.0_0.1.2/packer_default_virtualbox.box",
  ]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = 2
    virtualbox.memory = 12 * 1024
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.shell = "/bin/sh"
end
