Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.box = "emulate/openbsd-7.3"
  config.vm.ignore_box_vagrantfile = true
  config.vm.box_check_update = false
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "f1e59cab9a9b744c89f57abe8912629c75aa36743bc635cb800af34aa88c6d4a"
  config.vm.box_url = [
    "https://app.vagrantup.com/emulate/boxes/openbsd-7.3/versions/1.0.0/providers/virtualbox.box",
    "https://github.com/mario-campos/emulate/releases/download/openbsd-7.3_1.0.0/virtualbox.box",
  ]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = 2
    virtualbox.memory = 12 * 1024
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.shell = "ksh -l"
end
