name: emulate
description: Emulate unsupported operating systems using QEMU.
inputs:
  operating-system:
    description: The operating-system specifier.
    required: true
runs:
  using: composite
  steps:
  - name: Boot guest ${{ inputs.operating-system }}.
    shell: bash
    run: |
      cd "$RUNNER_TEMP"
      vagrant init "emulate/${{ inputs.operating-system }}"
      sudo nice -n -20 vagrant up
      echo "BASH_ENV=$GITHUB_ACTION_PATH/BASH_ENV" >> "$GITHUB_ENV"
