name: emulate
description: Emulate unsupported operating systems using QEMU.
inputs:
  operating-system:
    description: The operating-system specifier.
    required: true
runs:
  using: composite
  steps:
  - name: Boot guest ${{ inputs.operating-system }}.
    shell: bash
    working-directory: ${{ runner.temp }}
    env:
      EMULATE_OPERATING_SYSTEM: ${{ inputs.operating-system }}
    run: |
      case "$EMULATE_OPERATING_SYSTEM" in
        openbsd-latest) EMULATE_OPERATING_SYSTEM=openbsd-7.1 ;;
        freebsd-latest) EMULATE_OPERATING_SYSTEM=freebsd-13.0 ;;
        netbsd-latest)  EMULATE_OPERATING_SYSTEM=netbsd-9.2 ;;
      esac

      cd "$GITHUB_ACTION_PATH/$EMULATE_OPERATING_SYSTEM"
      vagrant up

      echo "BASH_ENV=$GITHUB_ACTION_PATH/BASH_ENV" >> "$GITHUB_ENV"
      echo "EMULATE_VAGRANT_PATH=$GITHUB_ACTION_PATH/$EMULATE_OPERATING_SYSTEM" >> "$GITHUB_ENV"
