Vagrant.configure("2") do |config|
  config.vm.box = "dragonflybsd/dragonfly520"
  config.vm.box_version = "0.0.1"
  config.vm.box_check_update = false

  config.vm.guest = "dragonflybsd"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 7 * 1024 * 0.75
  end

  config.ssh.insert_key = false
end
