Vagrant.configure("2") do |config|
  config.vm.box = "emulate/openbsd-7.6"
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "363defef19b581e76e3720f64a558f96b67a550449f5b5499c8fc438dcdda296"
  config.vm.box_url = "https://github.com/mario-campos/emulate-images/releases/download/openbsd-7.6_2/packer_default_virtualbox_amd64.box"
end
