Vagrant.configure("2") do |config|
  config.vm.box = "generic/dragonflybsd6"
  config.vm.box_version = "3.4.2"
  config.vm.guest = "dragonflybsd"
  config.vm.box_check_update = false
  config.vm.provision "shell", inline: "pkgin -y install git"
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 7 * 1024 * 0.75
  end
end
