Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.box = "generic/openbsd6"
  config.vm.box_version = "3.4.2"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.check_guest_additions = false
    virtualbox.memory = 14 * 1024 * 0.75
    virtualbox.cpus = 2
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
end
