Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.shell = "ksh -l"
end
