Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.box = "emulate/openbsd-7.0"
  config.vm.ignore_box_vagrantfile = true
  config.vm.box_check_update = false
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "e9dbde3273d48adeabf050d163b0f50b848b7846f030a2a037457388e4a42dac"
  config.vm.box_url = [
    "https://app.vagrantup.com/emulate/boxes/openbsd-7.0/versions/0.1.3/providers/virtualbox.box",
    "https://github.com/mario-campos/emulate/releases/download/openbsd-7.0_0.1.3/packer_default_virtualbox.box",
  ]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.cpus = 2
    virtualbox.memory = 12 * 1024
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.shell = "ksh -l"
end
