Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"
  config.vm.box_version = "3.4.2"
  config.vm.provision "shell", inline: "pkg_add bash git"
  config.vm.provider :libvirt do |libvirt|
    libvirt.name = "OpenBSD-6.9"
    libvirt.driver = "qemu"
    libvirt.memory = 6144 # 6 GiB
  end
end
