Vagrant.configure("2") do |config|
  config.vm.guest = "openbsd"

  config.vm.box = "generic/openbsd6"
  config.vm.box_version = "3.4.2"
  config.vm.box_check_update = false

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.check_guest_additions = false
    virtualbox.memory = 14 * 1024 * 0.75
    virtualbox.cpus = 2
  end

  config.ssh.username = "runner"
  config.ssh.insert_key = false
  config.ssh.sudo_command = "doas %c"
  config.ssh.forward_env = [
    "CI",
    "GITHUB_WORKFLOW",
    "GITHUB_RUN_ID",
    "GITHUB_RUN_NUMBER",
    "GITHUB_JOB",
    "GITHUB_ACTION",
    "GITHUB_ACTIONS",
    "GITHUB_ACTOR",
    "GITHUB_REPOSITORY",
    "GITHUB_EVENT_NAME",
    "GITHUB_EVENT_PATH",
    "GITHUB_WORKSPACE",
    "GITHUB_SHA",
    "GITHUB_REF",
    "GITHUB_HEAD_REF",
    "GITHUB_BASE_REF",
    "GITHUB_SERVER_URL",
    "GITHUB_API_URL",
    "GITHUB_GRAPHQL_URL",
    "RUNNER_NAME",
    "RUNNER_OS",
    "RUNNER_TEMP",
    "RUNNER_TOOL_CACHE"
  ]
end
