Vagrant.configure("2") do |config|
  config.vm.box = "generic/openbsd6"
  config.vm.box_version = "3.4.2"
  config.vm.box_check_update = false

  config.vm.guest = "openbsd"
  config.vm.provision "shell", inline: <<-SHELL
    sudo sh -c "echo permit nopass nolog keepenv $USER > /etc/doas.conf"
    pkg_add git
  SHELL
  config.vm.provider :libvirt do |libvirt|
    libvirt.driver = "qemu"
    libvirt.memory = 7 * 1024 * 0.75
  end

  config.ssh.insert_key = false
end
