Vagrant.configure("2") do |config|
  config.vm.guest = "netbsd"

  config.vm.box = "emulate/netbsd-9.2"
  config.vm.ignore_box_vagrantfile = true
  config.vm.box_check_update = false
  config.vm.box_download_checksum_type = "sha256"
  config.vm.box_download_checksum = "d7dca4a3dcb31202ab66ac7c54eacca9b4dcd6bee1a2cac2e346fc3df3dd9662"
  config.vm.box_url = [
    "https://app.vagrantup.com/emulate/boxes/netbsd-9.2/versions/0.1.1/providers/virtualbox.box",
    "https://github.com/mario-campos/emulate/releases/download/netbsd-9.2_0.1.1/packer_default_virtualbox.box",
  ]

  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.provider "virtualbox" do |virtualbox|
    virtualbox.check_guest_additions = false
  end

  config.ssh.username = "root"
  config.ssh.insert_key = false
  config.ssh.shell = "/bin/sh"
end
